# Header
menu:
  主页: /
  #归档: /archives
  #学习笔记: /categories/article/
  #实验项目: /categories/project/
  所有日志: /list
  关于: /about
  友情链接: /links
  
rss: /atom.xml #http://feed.feedsky.com/nshen

# Content
excerpt_link: Read More
fancybox: true
mathjax: false

# Sidebar
sidebar: bottom #right
widgets:
- category
#- tag
- tagcloud
#- archive
#- recent_posts
#- links

# Links

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Baidu share
baidushare: true

# Duoshuo
duoshuo_shortname: nshen121
